Questionnaire\Accessibility\Numeric: Instructions not programmatically associated with field
remotelearner/moodle-mod_questionnaire pull request #496
Opened 2023-07-14 09:01 UTC by tailetan

Hi @mchurchward,

We are from the Open University and would like to propose the change that support the accessibility screen reader to read out the instruction of the Numeric questions.
Could you please review this commit and let us know if you have any concerns?

Thank you indeed.

2023-07-31 13:29 UTC, rezeau approved these changes
Tested with Windows NVDA on Firefox and MS Bing browsers.
Works as expected.

2023-09-18 10:16 UTC, mchurchward requested changes
Can you rebase this with MOODLE_401_STABLE?
I don't think the ".idea" directory should be part of this.
Is there a way to update the Behat test to verify this?

2023-09-21 10:54 UTC, tailetan commented
I have updated behat test and rebased this with MOODLE_401_STABLE. Could you merge this commit, @mchurchward ? Thanks

2023-09-21 13:12 UTC, mchurchward approved these changes

2023-09-21 13:12 UTC, merged