Questionnaire\Accessibility\Rate: table does not have a programmatically associated caption
remotelearner/moodle-mod_questionnaire pull request #497
Opened 2023-07-14 09:13 UTC by lamtranb

Hi @mchurchward 

We are from the Open University and would like to propose the change that support the accessibility screen reader for Rate question

Data tables SHOULD have a programmatically associated caption or name. Screen readers read the caption or name of the table when users navigate to the table, giving users a sense of what the table is about. The caption element is the most straightforward way to give a name to a table. The recommendation is to add an appropriate caption to the table using the <caption> tag with question text.

Could you please review this commit ?

Many thanks.

2023-07-31 13:51 UTC, rezeau approved these changes
Tested with Windows NVDA on Firefox and MS Bing browsers.
Works as expected.

2023-09-18 10:20 UTC, mchurchward requested changes
Code changes look good.
Can you rebase and resubmit with MOODLE_401_STABLE?
Is there a way to update the Behat test to verify this change?

2023-09-18 10:27 UTC, lamtranb commented
Hi @mchurchward,

I will rebase and resubmit with MOODLE_401_STABLE.
For behat test for accessibility, I think we can use xpath to check if elements exist or elements have correct attributes. I will add behat tests as your suggestion. If you have any better idea, please let me know.

Thanks.

2023-09-20 12:11 UTC, mchurchward approved these changes

2023-09-20 12:11 UTC, merged