Questionnaire/Accessibility: Check boxes missing group label
remotelearner/moodle-mod_questionnaire pull request #501
Opened 2023-08-01 11:40 UTC by emanoylov

Changes related to accessibility so that the checkbox answers are better-associated with the question text asked.

E.g. if the question is "Are Strawberries berries?" and the options are Yes/No/Other the possible responses are read out by the screen reader as:

"Are strawberries berries? Yes"
"Are strawberries berries? No"
"Are strawberries berries? Other"

2023-08-03 09:31 UTC, rezeau commented
Tested under Windows with NVDA screenreader and Firefox and MS Edge browsers.
This works as expected. However it introduces changes in a large number of files.

2023-09-18 11:07 UTC, mchurchward requested changes
Per Joseph's comment, I think this could be done in a much simpler way, that should primarily impact just the question types in question, without the need for passing the $pagetags around all of the functions. Definitely needed though.

2023-09-20 14:00 UTC, emanoylov commented
I've minimised the changes to the check box question type as per the comments. Please review again.

2023-09-20 14:11 UTC, mchurchward reviewed
I'm not clear on why the main question file essay question section, and the question and response container templates were modified. Can you explain?

2023-09-20 15:52 UTC, emanoylov commented
The changes are after the QUESESSAY if statement; it just splits the formatting of $content to avoid unnecessary formatting for qlegend.
The question container is modified to add qlegend to the legend and to make the legends consistent as some were missing qnum.
The response templates are modified for consistency.

2023-09-21 12:19 UTC, mchurchward commented
> The changes are after the QUESESSAY if statement
Ah yes. Sorry, I read that wrong.

> The question container is modified to add qlegend to the legend and to make the legends consistent as some were missing qnum.
Okay. So then this fix is for more that checkbox questions? Is that correct? If so, can you update the description to reflect this?

2023-09-21 15:12 UTC, emanoylov commented
@mchurchward  I've updated the description. Thanks.

2023-09-26 15:15 UTC, mchurchward approved these changes

2023-09-26 15:16 UTC, merged