restore_radar_charttype rebased to MOODLE_401_STABLE
remotelearner/moodle-mod_questionnaire pull request #510
Opened 2023-09-26 20:42 UTC by rezeau

This PR replaced obsolete branch #490

2023-10-03 17:33 UTC, mchurchward requested changes
Can Behat tests be updated/added to verify these?

2023-10-03 17:33 UTC, mchurchward commented on classes/feedback_form.php
> +        $sql = 'SELECT COUNT(*) ' .
This should be simplified to a:
$numfeedbacksections = $DB->count_records('questionnaire_fb_sections', ['surveyid' => $sid]);
No need to create an SQL statement.

2023-10-03 17:33 UTC, mchurchward commented on classes/feedback_form.php
> +        }
Does $feedbackoptions[2] need to be set to an empty string if the count is one or less?

2023-10-03 17:39 UTC, mchurchward commented on classes/feedback_form.php
> +        }
Also, when I looked at the results of an existing feedback, I got the message:
<b>Deprecated</b>:  explode(): Passing null to parameter #2 ($string) of type string is deprecated in <b>/mod/questionnaire/drawchart.php</b> on line <b>107</b><br />

2023-10-04 09:42 UTC, rezeau commented on classes/feedback_form.php
> +        }
I don't understand how this can happen. Anyway, I've added a check to avoid potential error message: if ($label !== null) ...

2023-10-04 09:54 UTC, rezeau commented
@mchurchward wrote "Can Behat tests be updated/added to verify these?"
I've checked that the existing Behat test _add_multi_feedback_with_sections.feature_ works OK with this PR. 
Do you prefer me to update that Behat test with my PR new features OR create a new test?

2024-02-23 16:44 UTC, mchurchward commented
Hi Joseph. Sorry it has taken so long to get back to this.
I'm having trouble testing it. I have existing questionnaires with feedback options already in the database.
The questionnaire has a normal rate question.
But when I try to access the feedback for editing, I get the message:
_"Feedback options are available if your questionnaire contains the following question types and question settings: Radio buttons; Dropdown box; Yes/No; or Rate (normal or Osgood scale). Those questions must be set as Required, their Question Name field must NOT be empty and the Possible answers choices must contain a value. "_
This error happens on the current MOODLE_401_STABLE branch as well as the one you have provided here.

What am I doing wrong?

2024-02-26 14:12 UTC, rezeau commented
@mchurchward I've just tested my PR #510 on my local moodle test site running Moodle 4.3.3+ (Build: 20240215). It works as expected.
You write:: "_The questionnaire has a normal rate question.
But when I try to access the feedback for editing, I get the message:
"Feedback options are available if your questionnaire contains the following question types and question settings: Radio buttons; Dropdown box; Yes/No; or Rate (normal or Osgood scale). Those questions must be set as Required, their Question Name field must NOT be empty and the Possible answers choices must contain a value. ""_
1.- Are you positive that your questionnaire obeys _all the conditions_ mentioned in the Feedback options warning message?
2.- If you try your to add Feedback to your questionnaire _without_ using my PR, are you getting the same message? My PR has nothing to do with those Feedback requirements, i.e. it does not add any extra requirement to the list.

2024-02-27 15:21 UTC, rezeau commented
@mchurchward Should I wait for #542 and @lucaboesch 's suggestion :: "_A branch MOODLE_403_STABLE in your repository would be highly appreciated_" before continuing testing this #510 ?

2024-10-11 09:08 UTC, joostelshoff commented
@mchurchward What is the current status of this fix?

2025-06-10 08:50 UTC, benjamin-feron commented
Hello, is there any chance to see this PR merged ?

2025-06-10 17:50 UTC, rezeau commented
@benjamin-feron Probably very little chance.

2025-11-26 21:56 UTC, closed without merging