Questionnaire different ≤ 4.2 and ≥ 4.3 activity completion behat tests …
remotelearner/moodle-mod_questionnaire pull request #523
Opened 2023-10-15 17:52 UTC by lucaboesch

… fix #522 .

Dear @mchurchward this pull request lets pass the automated tests again.

Best,
Luca

2023-10-16 13:47 UTC, rezeau commented
Just tested this PR on my local Moodle site running Moodle 4.3. PR Works as expected, the first scenario (_Check questionnaire completion feature in web for Moodle ≤ 4.2_) is skipped and the "_Check questionnaire completion feature in web for Moodle ≥ 4.3_" scenario is passed OK.
A _very minor_ grievance: I am running those behat tests on my Windows box, with profile=geckodriver and the test begins to show in an Acceptance  text site window but, when scenario 1 is skipped, then that window closes and does not re-open. However, if I add the --format=pretty parameter I can follow all the steps in my Windows shell window, so that's OK.

2023-10-30 18:52 UTC, mchurchward commented
@lucaboesch thanks for this. Do you know why we need to add "xpath" for 4.3? This seems to be something that would not be desirable.

2023-10-30 19:36 UTC, lucaboesch commented
And I click on "3" radio wouldn't execute any more, @mchurchward, I tried it...

2023-10-31 12:20 UTC, mchurchward commented
But it does work in other places, like:
questionnaire_activity_completion.feature
add_feedback.feature
add_multi_feedback_with_sections.feature

That makes me think there is something wrong with the display of that radio. There may need to be a fix in the display code.

2023-10-31 13:38 UTC, mchurchward commented
Also, the error that was [highlighted here](https://github.com/PoetOS/moodle-mod_questionnaire/actions/runs/6436573851/job/17480171307?pr=520#step:17:221) was for "Completion tracking". So the radio error came up after that was fixed?

2023-10-31 16:03 UTC, mchurchward commented
@lucaboesch I just tested this locally, and the only change it needs is for the "Completion tracking". The radio buttons work fine.

2023-10-31 16:23 UTC, lucaboesch commented
It would be of great help if you could paste in the modified lines here, @mchurchward

2023-10-31 16:57 UTC, lucaboesch commented
I had it run again.
The Moodle Plugin CI run error states

```
001 Scenario: Check questionnaire completion feature in web for Moodle ≥ 4.3. # /home/runner/work/moodle-mod_questionnaire/moodle-mod_questionnaire/moodle/mod/questionnaire/tests/behat/questionnaire_activity_completion.feature:70
      And I click on "Yes" "radio"                                            # /home/runner/work/moodle-mod_questionnaire/moodle-mod_questionnaire/moodle/mod/questionnaire/tests/behat/questionnaire_activity_completion.feature:111
        Behat\Mink\Exception\UnsupportedDriverActionException: Behat\Mink\Driver\BrowserKitDriver supports clicking on links and submit or reset buttons only. But "input" provided in /home/runner/work/moodle-mod_questionnaire/moodle-mod_questionnaire/moodle/vendor/behat/mink-browserkit-driver/src/BrowserKitDriver.php:468
```

2023-10-31 17:03 UTC, mchurchward requested changes

2023-10-31 17:03 UTC, mchurchward commented on tests/behat/questionnaire_activity_completion.feature
> +    And I am on the "Test questionnaire completion" "questionnaire activity editing" page
I think the lines below can be simplified to:

    And I expand all fieldsets
    And I set the following fields to these values:
      | Add requirements                                      | 1 |
      | Student must submit this questionnaire to complete it | 1 |

This is from examples in core.

2023-10-31 17:03 UTC, mchurchward commented on tests/behat/questionnaire_activity_completion.feature
> +    And I set the field with xpath "//input[@type='radio' and @id='auto-rb0001']" to "1"
The code:
    And I click on "Yes" "radio"
    And I click on "Three" "radio"
 still works for me running Behat locally. I don't think this and the next change are needed.

2023-10-31 17:04 UTC, mchurchward commented on tests/behat/questionnaire_activity_completion.feature
> +    And I set the field with xpath "//input[@type='radio' and @id='auto-rb0001']" to "1"
I wonder if its due to "master". The CI should be changed to MOODLE_403_STABLE now that it has been released.

2023-10-31 17:13 UTC, mchurchward commented
> I had it run again. The Moodle Plugin CI run error states
> 
> ```
> 001 Scenario: Check questionnaire completion feature in web for Moodle ≥ 4.3. # /home/runner/work/moodle-mod_questionnaire/moodle-mod_questionnaire/moodle/mod/questionnaire/tests/behat/questionnaire_activity_completion.feature:70
>       And I click on "Yes" "radio"                                            # /home/runner/work/moodle-mod_questionnaire/moodle-mod_questionnaire/moodle/mod/questionnaire/tests/behat/questionnaire_activity_completion.feature:111
>         Behat\Mink\Exception\UnsupportedDriverActionException: Behat\Mink\Driver\BrowserKitDriver supports clicking on links and submit or reset buttons only. But "input" provided in /home/runner/work/moodle-mod_questionnaire/moodle-mod_questionnaire/moodle/vendor/behat/mink-browserkit-driver/src/BrowserKitDriver.php:468
> ```

I wonder if that is a Chrome issue with Behat? Maybe try:
        run: moodle-plugin-ci behat
(drop the --profile chrome part)?

2023-11-02 18:39 UTC, mchurchward commented
@lucaboesch I figured out the problem. Radio buttons should not use "I click". They need a "Set field to" instead. But, they do work if "@javascript" is specified, and it wasn't for the new 4.3 scenario. In any case, the correct fix is to use "set field to".
See my [commit here](https://github.com/PoetOS/moodle-mod_questionnaire/commit/c43b770932e68fb167318a92510cf79398acf6c7). It does the "set field" and additionally I simplified the scenarios by moving the duplicate steps to the background. If you want to update your PR accordingly, I will merge it in.

2023-11-02 22:19 UTC, lucaboesch commented
Yeah, @mchurchward, but the point was to make the test passing for Moodle ≥ 4.3 as well as Moodle ≤ 4.2 so you don't resolve in leaving out those versions in ci.yml.
This updated pull request fits all needs and supports PHP 7.4, 8.0 and 8.1.

Best,
Luca

2023-11-07 16:17 UTC, mchurchward approved these changes

2023-11-07 16:18 UTC, mchurchward commented
Thanks Luca. Of course once we add PHP8.2 to the CI, there will be a huge mess. :-0

2023-11-07 16:18 UTC, merged