579 Fix dataformatlib.php No such file or dir
remotelearner/moodle-mod_questionnaire pull request #587
Opened 2024-07-29 08:57 UTC by leonstr

Remove require_once() for a core file removed in Moodle 4.4 (MDL-80409). This plugin requires Moodle 4.1 and so instead can use the replacement introduced in Moodle 3.9, dataformat::download_data().

Proposed fix for #579

2024-08-21 19:20 UTC, mchurchward requested changes
Thank you for this. Can you rebase with the latest MOODLE_401_STABLE to re-enable the CI tests?

2024-08-22 16:17 UTC, leonstr commented
Rebased.

2024-08-27 20:20 UTC, mchurchward commented
Your PR still includes commits from other changes than this one. The PR needs to just include the commit(s) for this PR.
You need to pull the latest MOODLE_401_STABLE locally, then rebase your branch on top of that.

2024-08-28 11:03 UTC, leonstr commented
I've tried rebasing this again, I can only see my commit now. Please let me know if there are still issues with this.

2024-08-28 19:24 UTC, mchurchward approved these changes
Thanks for your submission.

2024-08-28 19:24 UTC, merged