Questionnaire: Print attempt view - add a 'Print' button
remotelearner/moodle-mod_questionnaire pull request #588
Opened 2024-08-15 10:28 UTC by toanlamt

2024-08-21 17:11 UTC, mchurchward commented
Can you rebase with the latest MOODLE_401_STABLE? I just fixed the CI.

2024-08-26 06:23 UTC, tailetan commented
I rebased with the latest MOODLE_401_STABLE. CC @mchurchward

2024-08-27 20:18 UTC, mchurchward requested changes
Your PR still includes commits from other changes than this one. The PR needs to just include the commit(s) for this PR.
You need to pull the latest MOODLE_401_STABLE locally, then rebase your branch on top of that.
This may have been caused by a recent force push, apologies.

2024-08-28 02:48 UTC, tailetan commented
Rebased again, note that there is a deprecated behat step fail in MOODLE_404_STABLE ('I add a "Questionnaire" to section "1"'). CC @mchurchward

2025-02-20 20:23 UTC, mchurchward commented
What page is this adding a print button to? The only one I can see that doesn't currently have a print button is the myreport summary page. This change doesn't appear to be that.

2025-03-11 08:31 UTC, tailetan commented
@mchurchward Thanks for your review! Actually, the "Print" button is on the report page. If you're on the myreport page, you need to click "Print this Response" to navigate to the report page. The "Print" button is located at the bottom of that page. Please see the attached video.

Uploading 2025-03-11_15h20_07.mp4…

2025-03-19 17:52 UTC, mchurchward approved these changes

2025-03-19 17:53 UTC, merged