Questionnaire: option to auto-delete responses after X time
remotelearner/moodle-mod_questionnaire pull request #590
Opened 2024-08-15 10:37 UTC by toanlamt

2024-08-21 16:53 UTC, mchurchward commented
I'm not sure I agree with this change. If I'm understanding correctly, it will delete responses automatically in the background if they are older than a specified time? What is the use case for this?

2024-08-28 19:43 UTC, mchurchward commented
This issue needs to describe what it is for, and how it provides the solution. Use cases / user stories would be helpful.
Does this type of functionality exist in any Moodle core activities?

2024-09-09 14:48 UTC, mchurchward commented
I will accept this if a global questionnaire setting is added to enable/disable this new function. It should be defaulted to disabled, requiring any site to turn it on before it takes affect.
Also, there are new conflicts that need to be fixed.

2024-09-10 02:38 UTC, tailetan commented
I will update and get back to you soon. Thanks

2024-09-10 15:34 UTC, mchurchward commented
And one more requirement, sorry. Any specific questionnaire should be able to prevent it's responses from being deleted automatically. That is, if the automatic deletion is enabled for questionnaire globally, then any questionnaire can have a setting that prevents this. And, existing questionnaires should have that disabled by default to protect them.

2024-09-17 09:15 UTC, tailetan commented
I have just updated the commit based on the @mchurchward's requirement, please review again. Thanks

2025-02-19 19:19 UTC, mchurchward commented on locallib.php
> +             WHERE q.removeafter <> 0 AND (q.removeafter < :currettime - qr.submitted)";
:currettime should be :currenttime

2025-02-19 19:27 UTC, mchurchward commented on locallib.php
> +                $DB->execute($sql, $params);
Use a Moodle $DB 'delete_records' API function instead of execute.

2025-02-19 19:29 UTC, mchurchward requested changes
See inline comments.

2025-03-10 09:13 UTC, tailetan commented
Ready for review @mchurchward

2025-03-10 15:45 UTC, mchurchward commented
> Ready for review @mchurchward

Thanks. In the future, don't squash a review commit fix. It is very difficult to determine what you changed since the review when that is done. Instead, leave them as new commits in the PR, and they can be squashed with the PR.

2025-03-19 17:41 UTC, mchurchward requested changes
Please review and address inline comments as needed.

2025-03-19 17:41 UTC, mchurchward commented on mod_form.php
> +    public function create_remove_options() {
This function doesn't appear to be used anywhere. It may be a duplicate of locallib::questionnaire_create_remove_options()? If so, it may make sense to use this one rather than the one in locallib?

2025-03-19 17:41 UTC, mchurchward commented on lang/en/questionnaire.php
> +$string['removeoldresponsesafter'] = 'Manage old responses after';
This should use "Delete" or "Remove" instead of "Manage" for clarity.

2025-03-19 17:41 UTC, mchurchward commented on settings.php
> +    $options = [
Ideally, this setting should appear before the previous setting ("questionnaire/removeoldresponses"), since it directly impacts that one.

2025-03-19 17:41 UTC, mchurchward commented on backup/moodle2/backup_questionnaire_stepslib.php
> +            'closedate', 'resume', 'navigate', 'grade', 'sid', 'timemodified', 'completionsubmit', 'autonum', 'removeafter'));
Have you tested a restore of an older questionnaire backup that doesn't have the removeafter setting to ensure there is not an issue?

2025-03-20 09:12 UTC, tailetan commented on backup/moodle2/backup_questionnaire_stepslib.php
> +            'closedate', 'resume', 'navigate', 'grade', 'sid', 'timemodified', 'completionsubmit', 'autonum', 'removeafter'));
I have just tested and it works as expected

2025-03-20 09:13 UTC, tailetan commented
@mchurchward this is now ready for review again.

2025-06-05 14:56 UTC, mchurchward commented
Sorry. There is a conflict I can't see for some reason. Can you check that your PR branch is up to date with the current MOODLE_404_STABLE branch?

2025-06-06 04:32 UTC, tailetan commented
@mchurchward Just rebased. Please review it again. Thanks

2025-06-09 14:52 UTC, mchurchward commented
This was resolved with [PR634](https://github.com/PoetOS/moodle-mod_questionnaire/pull/634)

2025-06-09 14:52 UTC, closed without merging