594 Fix formChild is null
remotelearner/moodle-mod_questionnaire pull request #595
Opened 2024-08-22 21:12 UTC by leonstr

When a student completed a questionnaire then shown the "Thank you for completing this Questionnaire" page there was a JavaScript error:

  Uncaught TypeError: formChild is null

This was because the JavaScript for the questions form was being inadvertently loaded for the Thank you page where this form is not present.

2024-08-27 20:12 UTC, mchurchward requested changes
This will need to rebased with the latest MOODLE_401_STABLE so that only this PR's commit is present.

2024-08-28 10:47 UTC, leonstr commented
Apologies, rebased, hopefully this is correct now.

2024-08-28 11:01 UTC, leonstr commented
Maybe it is correct after all, please let me know if there are still issues with this.

2024-08-28 19:29 UTC, mchurchward commented
There was a fix added to the [javascript here](https://github.com/PoetOS/moodle-mod_questionnaire/commit/852486f30b967d5d61847dfaff9ec8cd23f4c11f). This may already fix the problem you describe?

2024-08-28 19:47 UTC, leonstr commented
> There was a fix added to the [javascript here](https://github.com/PoetOS/moodle-mod_questionnaire/commit/852486f30b967d5d61847dfaff9ec8cd23f4c11f). This may already fix the problem you describe?

No, in fact this issue only occurs once that fix has been applied. Fix 852486f allows the form checker to be run with Moodle 4.4 (instead of getting a console error), but this means a long-time bug re-emerges due to the form checker being incorrectly loaded for the "Thank you" page. If in doubt, install the latest MOODLE_401_STABLE of mod_questoinnaire and follow the steps in #594.

2024-08-28 20:10 UTC, mchurchward commented
I don't get that error using the latest MOODLE_401_STABLE.

2024-08-28 20:35 UTC, leonstr commented
> I don't get that error using the latest MOODLE_401_STABLE.

On the Thank You page? That's a mystery since there's no DOM element with the ID specified by the form checker code.

I've just retested, on Moodle 4.4.2+ (Build: 20240823) with mod_questionnaire 5c0dbe8 and still see the error if I follow the steps form #594 (slightly different error because it's a different browser):

![typeerror](https://github.com/user-attachments/assets/6fdf7483-991c-47b2-9629-d371185e963d)

2024-08-29 15:17 UTC, mchurchward commented
Ah. Okay. I didn't realize you meant in the console. Yes, I do see that.

2024-08-29 15:18 UTC, mchurchward approved these changes
Thanks for the clarification.

2024-08-29 15:18 UTC, merged