Add new question type file
remotelearner/moodle-mod_questionnaire pull request #599
Opened 2024-08-28 12:24 UTC by srobotta

Hi Mike,

this is a new pull request for the new file type question and replaces https://github.com/PoetOS/moodle-mod_questionnaire/pull/559
The original work on the file type has been done by Laurent David (https://github.com/laurentdavid). He introduced this question/response type and also created https://github.com/PoetOS/moodle-mod_questionnaire/pull/471
Luca Bösch added behat tests for the new file type.
I finally fixed a few issues from the original work from Laurent:
- deletion of left over data when a response or the whole questionnare is deleted.
- possibility to have multiple file type questions in one questionnaire.

I have taken your latest MOODLE_401_STABLE branch from the plugin and our codebase from BFH where this is already included and created this pull request that just contains the file type.

2024-08-28 20:24 UTC, mchurchward commented
Thank you for all the effort you have put into this. I will review this happily.

2024-08-29 07:22 UTC, srobotta commented
Just rebased to the latest MOODLE_401_STABLE branch.

2025-02-20 19:25 UTC, mchurchward requested changes
I know this is old, but I was just testing it on MOODLE_404_STABLE and it didn't work.
I had a number of odd issues.

1. If I saved a response instead of submitting, when I went to resume the questionnaire, my file was not in the file question.
2. If I then uploaded it again, and submitted, I received the error "Undefined property: stdClass::$itemid" from the responsetype/file class when it went to delete the old response on line 136.
3. When I did it again, and submitted the first time, it worked. But the response page showed me a question response to rate question from another questionnaire.
4. I believe this will need backup and restore support code added?

2025-11-17 16:01 UTC, srobotta commented
This is obsolete as of [PR #681](https://github.com/PoetOS/moodle-mod_questionnaire/pull/681).

2025-11-17 16:01 UTC, closed without merging