Amend README.txt to reflect actual state.
remotelearner/moodle-mod_questionnaire pull request #601
Opened 2024-08-29 21:01 UTC by lucaboesch

2024-08-30 15:51 UTC, mchurchward requested changes

2024-08-30 15:51 UTC, mchurchward commented on README.txt
> +The current stable branch is MOODLE_404_STABLE, and supports Moodle 4.4 and up.
Not completely true. The current stable branch (aside from naming) is MOODLE_401_STABLE. It supports Moodle 4.1 through 4.4.
MOODLE_404_STABLE is the current development branch, for the next stable release, and supports Moodle 4.4 and targeting 4.5.

2024-08-30 20:46 UTC, lucaboesch commented
My point being: the current one (both MOODLE_401_STABLE as well as in MOODLE_400_STABLE branch, maybe the one in MOODLE_404_STABLE, too) ought to be amended.

2025-02-19 22:19 UTC, lucaboesch commented
I think it is accurate now.
Also, this pull request lets your Plugin CI tests turn green again.

2025-02-20 16:37 UTC, lucaboesch commented
Rebased to MOODLE_404_STABLE branch

2025-02-20 20:29 UTC, mchurchward commented
What's the change to "tests/custom_completion_test" for?
Also, there is now a conflict with the CI file.

2025-02-21 06:07 UTC, lucaboesch commented
_provider() classes have to be static now, @mchurchward

2025-02-21 06:30 UTC, lucaboesch commented
Rebased to MOODLE_404_STABLE branch

2025-02-21 15:31 UTC, mchurchward requested changes
Thanks for the changes. But...
Can you leave this PR to be just for the README?
Create a separate issue for the tests - I'm guessing that is something for 4.6? Since my CI isn't failing on that prior to that.
Don't include your CI changes yet. I will create a new development branch after this release to include main. Otherwise, we run the risk of the release branch failing.

2025-05-12 08:21 UTC, lucaboesch commented
I'm going to retry this pull request.

2025-06-05 14:58 UTC, lucaboesch commented
Rebased to most recent MOODLE_404_STABLE

2025-06-05 17:57 UTC, mchurchward requested changes
There are multiple changes here that have nothing to do with the README file. It looks like most of them are non-functional changes. If they are to be part of this PR, please update the description to reflect what is being done.

2025-06-06 04:55 UTC, lucaboesch commented
The changes to the functions signatures are in order to let the Moodle Plugin CI tests pass with main that is compatible with PHP 8.4.
If omitted, the readme file would receive a red CI badge.
If included, the CI badge is green.
So, the changws are not unrelated but required, Mike.

Best,
Luca

2025-07-14 15:43 UTC, mchurchward commented
> The changes to the functions signatures are in order to let the Moodle Plugin CI tests pass with main that is compatible with PHP 8.4. If omitted, the readme file would receive a red CI badge. If included, the CI badge is green. So, the changes are not unrelated but required, Mike.
> 
> Best, Luca

No. The changes to README will not trigger a failure, if the CI file is not changed. Please just provide the README file changes in this pull request.

For your other changes, I have created a new [MOODLE_500_STABLE](https://github.com/PoetOS/moodle-mod_questionnaire/tree/MOODLE_500_STABLE) branch. That will be the branch to support MOODLE 5 and PHP 8.4. Feel free to create a new PR with all the other changes against that branch. That branch will not support Moodle 4.

2025-07-14 17:10 UTC, lucaboesch commented
Okay, there you go.

2025-07-18 18:23 UTC, mchurchward commented
To make this simpler, I will make the requested changes.
I have fixed [MOODLE_404_STABLE](https://github.com/PoetOS/moodle-mod_questionnaire/commit/8a2c1f0a32237792c61178d46f127f35e97ee7ef).

This solves the MOODLE_404_STABLE branch.

Do you still have all of other changes you could apply to the MOODLE_500_STABLE branch? The CI changes and the fixes you did for PHP 8.4? I would welcome a new pull request for those.

2025-07-18 18:23 UTC, closed without merging

2025-07-19 07:32 UTC, lucaboesch commented
Yes, I do, @mchurchward.
I've opened separate pull requests against MOODLE_500_STABLE.
I'm away without dev instruments in holiday though and would not be able to make any changes right now.
Best,
Luca