Questionnaire: All branching shown in View your response
remotelearner/moodle-mod_questionnaire pull request #616
Opened 2024-11-06 09:13 UTC by toanlamt

**Context**: Enable the "Allow branching questions" setting. Create a radio question with multiple options, and add corresponding dependency questions for each option. The issue occurs when users answer the question and view their responses.

**Actual Results**: Users can see all of the dependency questions, which can be overwhelming.

**Expected Results**: Users should only see the dependency question that corresponds to the option they selected.

**Impacted Areas**: This fix only impacts the "View your response(s) > Individual responses" page.

2025-02-19 19:10 UTC, mchurchward commented on questionnaire.class.php
> +    public static function isDependentOnChoices(object $question, array $answers): bool {
Moodle [code style ](https://moodledev.io/general/development/policies/codingstyle#functions-and-methods)requires functions to be all lowercase, and separated by underscores.

2025-02-19 19:11 UTC, mchurchward requested changes
See inline comment

2025-03-11 07:00 UTC, tailetan commented
@mchurchward I have just pushed a new commit to fix your comment. Please review again. Thanks.

2025-03-14 14:54 UTC, mchurchward commented
This change does not seem to be working correctly.
I created dependencies, similar to the what is in the provided Behat test. 
1) Do you own a car yes/no
2.1) Yes - What colour is you car?
2.2) No - Will you buy a car this year?

If I answer "No" to question 1, my individual response shows the first dependency (colour) faded out with no answer, but not the second dependency answer which is the one I answered. See image:

![Screenshot 2025-03-14 at 10 52 45 AM](https://github.com/user-attachments/assets/a2004a7b-7050-4933-a66f-e08ed0d570dc)

2025-03-17 08:25 UTC, tailetan commented
@mchurchward, I have just tested that case, but it works as expected. 

See the video:
https://github.com/user-attachments/assets/e4acf931-0b49-41b6-a1ce-6d38db0de617
Did you set the dependencies correctly?

2025-03-17 14:30 UTC, mchurchward commented
> @mchurchward, I have just tested that case, but it works as expected.
> 
> See the video: https://github.com/user-attachments/assets/e4acf931-0b49-41b6-a1ce-6d38db0de617 Did you set the dependencies correctly?

Your video shows the "Yes" reply. The problem I posted is when "No" is answered.

2025-03-26 06:29 UTC, tailetan commented
@mchurchward yes, i also tested with no option. Please refer to the below attachment:
https://github.com/user-attachments/assets/a7bad7a0-bfd6-4578-8658-979b2bc8d46d
![image](https://github.com/user-attachments/assets/889bb11d-b8ce-47c8-8675-2b5ad6ab21d5)

**Setting**
![image](https://github.com/user-attachments/assets/442a9e6e-51db-4cd7-8da3-c547c1dc3e79)

2025-03-27 15:48 UTC, mchurchward commented
I still see the issue when I do the same.

Here is the question setup:
![Screenshot 2025-03-27 at 11 44 23 AM](https://github.com/user-attachments/assets/fc2ea055-152b-46cd-84f9-3bbd13be50e0)

Here are my answers:
![Screenshot 2025-03-27 at 11 44 44 AM](https://github.com/user-attachments/assets/ff851ba2-3737-4aa5-9ea5-c4f6bd84aaac)
![Screenshot 2025-03-27 at 11 44 54 AM](https://github.com/user-attachments/assets/fdd72bcd-2f47-4007-9ea1-7d7fbf8f719c)

And here is what I see on the response screen:
![Screenshot 2025-03-27 at 11 45 10 AM](https://github.com/user-attachments/assets/f96ddf3c-4600-4916-ba7d-0d4462c2a21a)


Note that this a new questionnaire with only one respondent.

2025-03-28 16:51 UTC, mchurchward commented
I added a [Behat test to test the specific case above](https://github.com/PoetOS/moodle-mod_questionnaire/commit/52a110e9a76b2d4ebda0f997712b55827fc5b38f).
It [fails the Behat ](https://github.com/PoetOS/moodle-mod_questionnaire/actions/runs/14133401447/job/39599197137#step:16:163)as well.

2025-04-29 07:31 UTC, oulxtacc1 commented
Hi @mchurchward 

Thanks for the feedback. I've reviewed my commit and investigated the issue. It turns out the problem was related to the logic that checks eligibility for the question. I've fixed it and pushed a new [commit](https://github.com/PoetOS/moodle-mod_questionnaire/compare/MOODLE_404_STABLE...NashTechOpenUniversity:moodle-mod_questionnaire:wip821631). Could you please review it again?

2025-04-29 07:34 UTC, toanlamt commented
Hi @mchurchward 

Thanks for the feedback. I've reviewed my commit and investigated the issue. It turns out the problem was related to the logic that checks eligibility for the question. I've fixed it and pushed a new [commit](https://github.com/PoetOS/moodle-mod_questionnaire/compare/MOODLE_404_STABLE...NashTechOpenUniversity:moodle-mod_questionnaire:wip821631). Could you please review it again?

2025-11-01 14:05 UTC, mchurchward approved these changes

2025-11-01 14:08 UTC, merged